#------------------------------------------------------------------------------------
# primaryGeneratorSetup.mac: Set up the primary generator environment
#  [Note] Geant4 Tutorial for Hep/Space Users: 2015.08.24 @Hiroshima 
#------------------------------------------------------------------------------------

## Particle type
/gps/particle geantino

## Kinematical information
/gps/energy    1.0 MeV
/gps/position  0.0  0.0  0.0 cm
/gps/direction 0.0  0.0  +1.0


