#---------------------------------------------------------------------
# primaryGeneratorSetup.mac: Set up the primary generator environment
#  [Note] Geant4 Tutorial for Hep/Medicine Users
#---------------------------------------------------------------------

## Particle type
/gun/particle ion
/gun/ion 55 137

## Enable radioactive decay of long-decay-time elements
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

## Kinematical information
/gun/energy    0.0 MeV               # For stationary decay
/gun/position  0.0  0.0  -5.0 cm
